apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - ../../base
  - externalsecret-db.yaml
  - externalsecret-admin.yaml
  - externalsecret-oauth.yaml
  - dashboard-provider.yaml
  - dashboard-configmap.yaml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: "7.3.7"
    releaseName: grafana
    valuesFile: values.yaml
