apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - externalsecret.yaml

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    version: "5.0.15"
    releaseName: minio
    valuesFile: values.yaml
