apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildOptions:
  - --enable-helm

helmCharts:
  - name: topolvm
    repo: https://topolvm.github.io/topolvm
    version: 12.1.0 # (指定版本)
    releaseName: topolvm
    namespace: kube-system # (TopoLVM 通常在 kube-system 命名空間)
    valuesFile: values.yaml

resources:
  - topolvm-storage-classes.yaml

patchesStrategicMerge:
  - controller-tolerations.yaml

labels:
  - pairs:
      app.kubernetes.io/name: topolvm
      app.kubernetes.io/part-of: detectviz-storage
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: storage

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
