apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildOptions:
  - --enable-helm

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.10.5
    releaseName: external-secrets
    namespace: external-secrets-system
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - cluster-secret-store.yaml

labels:
  - pairs:
      app.kubernetes.io/name: external-secrets-operator
      app.kubernetes.io/part-of: detectviz-security
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: secrets-management
      environment: production
      cluster: detectviz-production
    includeSelectors: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
  environment: production
  cluster: detectviz-production
