apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metallb-upstream.yaml

labels:
  - pairs:
      app.kubernetes.io/name: metallb
      app.kubernetes.io/part-of: detectviz-gitopsstructure
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: load-balancer

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
