apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ../base

helmCharts:
  - name: tempo
    valuesFile: values.yaml

patches:
  - path: patch-nodeselector-storage.yaml
    target:
      kind: (Deployment|StatefulSet)
