apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    version: "5.0.15"
    releaseName: minio
    # namespace 由 ApplicationSet destination 決定 (monitoring)
