apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ../../base
  - local-path-storage-class.yaml

helmCharts:
  - name: local-path-provisioner
    repo: https://charts.rancher.io
    version: "0.0.28"
    releaseName: local-path-provisioner
    namespace: kube-system
    valuesFile: values.yaml
