apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - ../../base
  - realm-configmap.yaml

# overlay 掛載 Bitnami Helm Chart 並套用生產環境 values
helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    version: "19.2.1"
    releaseName: keycloak
    valuesFile: values.yaml
