# Patch to deploy Prometheus to app-worker node
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-k8s
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/workload-apps: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
---
# Patch for Alertmanager to app-worker node
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager-main
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/workload-apps: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
