apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql-ha
    repo: https://charts.bitnami.com/bitnami
    version: "12.8.2"
    releaseName: postgresql
    namespace: postgresql
