apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: mimir-distributed
    repo: https://grafana.github.io/helm-charts
    version: 5.0.0
    releaseName: mimir
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true

commonLabels:
  app.kubernetes.io/name: mimir
  app.kubernetes.io/part-of: detectviz-monitoring
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: metrics-storage

labels:
  - pairs:
      environment: production
      app.kubernetes.io/part-of: detectviz-monitoring
    includeSelectors: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  environment: production
  cluster: detectviz-production
