apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: vault
      app.kubernetes.io/part-of: detectviz-security
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: secret-management

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"
