apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.10.5
    releaseName: external-secrets
    namespace: external-secrets-system
    valuesFile: values.yaml
    includeCRDs: true

labels:
  - pairs:
      app.kubernetes.io/name: external-secrets-operator
      app.kubernetes.io/part-of: detectviz-security
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: secrets-management

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
