apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - topolvm-storage-classes.yaml

labels:
  - pairs:
      app.kubernetes.io/name: topolvm
      app.kubernetes.io/part-of: detectviz-storage
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: storage

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
