apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

helmCharts:
  - name: alertmanager
    repo: https://prometheus-community.github.io/helm-charts
    version: "1.9.0"
    releaseName: alertmanager
    valuesFile: values.yaml
