# Helm values to configure Alertmanager to deploy to app-worker and use topolvm storage
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
spec:
  values:
    nodeSelector:
      node-role.kubernetes.io/workload-apps: "true"
    persistence:
      enabled: true
      storageClass: "topolvm-provisioner"
      size: 10Gi
