apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    version: "19.2.1"
    releaseName: keycloak
    # namespace 由 ApplicationSet 的 destination.namespace 決定 (keycloak)
