apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: loki-distributed
    repo: https://grafana.github.io/helm-charts
    version: 0.71.1
    releaseName: loki
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true

commonLabels:
  app.kubernetes.io/name: loki
  app.kubernetes.io/part-of: detectviz-monitoring
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: logs-aggregation

labels:
  - pairs:
      environment: production
      app.kubernetes.io/part-of: detectviz-monitoring
    includeSelectors: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
  environment: production
  cluster: detectviz-production
