apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - cert-manager-upstream.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/part-of: detectviz-security
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/component: certificate-management

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-2"
