# ExternalSecret to fetch Grafana Keycloak OAuth2 client secret from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-keycloak-oauth-creds
  namespace: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-keycloak-oauth
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: secret/data/grafana/oauth
        property: keycloak-client-secret
