# ExternalSecret to fetch DB credentials from Vault for Grafana
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-db-creds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-db-creds
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/data/grafana
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/grafana
        property: POSTGRES_PASSWORD
