# ExternalSecret to fetch DB credentials from Vault for Grafana
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-db-creds
  namespace: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-database
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_HOST: postgresql-pgpool.postgresql.svc.cluster.local:5432
        GF_DATABASE_NAME: grafana
        GF_DATABASE_USER: "{{ .dbUser }}"
        GF_DATABASE_PASSWORD: "{{ .dbPassword }}"
  data:
    - secretKey: dbUser
      remoteRef:
        key: secret/data/grafana/database
        property: user

    - secretKey: dbPassword
      remoteRef:
        key: secret/data/grafana/database
        property: password
