apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

resources:
  - ../base
  - externalsecret-db.yaml
  - externalsecret-admin.yaml
  - externalsecret-oauth.yaml
  - dashboard-provider.yaml
  - dashboard-configmap.yaml

patchesStrategicMerge:
  - patch-nodeselector.yaml
  - patch-values.yaml
