apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - externalsecret-db.yaml
  - externalsecret-admin.yaml
  - externalsecret-oauth.yaml

patchesStrategicMerge:
  - patch-nodeselector.yaml
  - patch-values.yaml
