apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql-ha
    repo: https://charts.bitnami.com/bitnami
    version: 14.2.0
    releaseName: postgresql
    namespace: detectviz
    valuesFile: values.yaml
    includeCRDs: false

commonLabels:
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/part-of: detectviz-platform
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: database

labels:
  - pairs:
      environment: production
      app.kubernetes.io/part-of: detectviz-platform
    includeSelectors: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
  environment: production
  cluster: detectviz-production
