apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret.yaml

helmCharts:
  - name: postgresql-ha
    repo: https://charts.bitnami.com/bitnami
    version: "12.8.2"
    releaseName: postgresql
    valuesFile: values.yaml
    # namespace 由 ApplicationSet 的 destination.namespace 決定 (postgresql)
